// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projects.Infrastructure;

namespace Projects.API.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Projects.Domain.AggregatesModel.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Area");

                    b.Property<int>("AreaId");

                    b.Property<string>("Avatar");

                    b.Property<int>("BrokerageOptions");

                    b.Property<string>("City");

                    b.Property<int>("CityId");

                    b.Property<string>("Company");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("FinMoney");

                    b.Property<string>("FinPercentage");

                    b.Property<string>("FinStage");

                    b.Property<string>("FormatBPFile");

                    b.Property<int>("Income");

                    b.Property<string>("Introduction");

                    b.Property<short>("OnPlatform");

                    b.Property<string>("OriginBPFile");

                    b.Property<string>("Province");

                    b.Property<int>("ProvinceId");

                    b.Property<int>("ReferenceId");

                    b.Property<DateTime>("RegisterTime");

                    b.Property<int>("Revenue");

                    b.Property<short>("ShowSecurityInfo");

                    b.Property<int>("SourceId");

                    b.Property<string>("Tags");

                    b.Property<DateTime>("UpdatetTime");

                    b.Property<int>("UserId");

                    b.Property<int>("Valuation");

                    b.HasKey("Id");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("Projects.Domain.AggregatesModel.ProjectContributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<int>("ContributorType");

                    b.Property<DateTime>("CreateTime");

                    b.Property<short>("IsCloser");

                    b.Property<int>("ProjectId");

                    b.Property<int>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("projectContributors");
                });

            modelBuilder.Entity("Projects.Domain.AggregatesModel.ProjectProperty", b =>
                {
                    b.Property<int>("ProjectId");

                    b.Property<string>("Key")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .HasMaxLength(100);

                    b.Property<string>("Text")
                        .HasMaxLength(512);

                    b.HasKey("ProjectId", "Key", "Value");

                    b.ToTable("projectProperties");
                });

            modelBuilder.Entity("Projects.Domain.AggregatesModel.ProjectViewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("ProjectId");

                    b.Property<int>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("projectViewers");
                });

            modelBuilder.Entity("Projects.Domain.AggregatesModel.ProjectVisibleRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProjectId");

                    b.Property<string>("Tags");

                    b.Property<short>("Visible");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("projectVisibleRules");
                });

            modelBuilder.Entity("Projects.Domain.AggregatesModel.ProjectContributor", b =>
                {
                    b.HasOne("Projects.Domain.AggregatesModel.Project")
                        .WithMany("Contributors")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Projects.Domain.AggregatesModel.ProjectProperty", b =>
                {
                    b.HasOne("Projects.Domain.AggregatesModel.Project")
                        .WithMany("Properties")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Projects.Domain.AggregatesModel.ProjectViewer", b =>
                {
                    b.HasOne("Projects.Domain.AggregatesModel.Project")
                        .WithMany("Viewers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Projects.Domain.AggregatesModel.ProjectVisibleRule", b =>
                {
                    b.HasOne("Projects.Domain.AggregatesModel.Project")
                        .WithOne("VisibleRules")
                        .HasForeignKey("Projects.Domain.AggregatesModel.ProjectVisibleRule", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
